### ISSUE TITLE
[ERR_MODULE_NOT_FOUND] in SvelteKit

### ISSUE THREAD

**Issue by FreddieRa** [grischaerbe/threlte#33]
I am trying to build the project with SvelteKit for deployment. Using `npm run dev` everything works, but when I try and build, I get:
```
> Using @sveltejs/adapter-cloudflare
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '[PATH]/node_modules/three/examples/jsm/postprocessing/EffectComposer' imported from [PATH]/.svelte-kit/output/server/entries/pages/index.svelte.js
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36)
> 500 /
    at file:///[PATH]/node_modules/@sveltejs/kit/dist/chunks/index5.js:409:11
    at visit (file:///PATH]/node_modules/@sveltejs/kit/dist/chunks/index5.js:583:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code 1
npm ERR! path [PATH]
npm ERR! command failed
npm ERR! command sh -c svelte-kit build

npm ERR! A complete log of this run can be found in:
npm ERR!   [USERPATH]npm/_logs/2022-02-18T04_48_45_935Z-debug.log
```

It does seem like this is a known issue from googling around, but the solution to lots of those was to move stuff from `devDependencies` to regular `dependencies`, but that hasn't worked. Any idea what's causing this?

**Comment by grischaerbe** [comment]
Hi @FreddieRa.

See the [Getting Started](https://github.com/grischaerbe/threlte#getting-started) section of the docs on how to get it running in SvelteKit.

**Comment by FreddieRa** [comment]
Hi again, I've started another project using Threlte and SvelteKit and I'm getting the same problem. I've done the getting started section, and have:
```js
 vite: {
    optimizeDeps: {
        exclude: ['three']
      },
    ssr: {
      noExternal: ['three']
    }
  }

```

But I still run into the identical error above. I cannpt remember how it got fixed last time. Do you have any insight?
