### ISSUE TITLE
Cannot destructure property 'registerInstance' of 'useInstancedMesh'

### ISSUE THREAD

**Issue by aozora** [grischaerbe/threlte#66]
Hi, I'm trying to create a scene  similar to this three.js example: https://github.com/mrdoob/three.js/blob/master/examples/webgl_instancing_dynamic.html

Given an array (particles) I use useFrame to change the position, rotation, and scale of each item in the array, and then I use that particle array like the following code:

```
<InstancedMesh {geometry} {material}>
  {#each particles as particle, index}
    <Instance id={String(index)} position={particle.position}
              rotation={particle.rotation}
              scale={particle.scale} />
  {/each}
</InstancedMesh>
```

However I get the error:

Uncaught (in promise) TypeError: Cannot destructure property 'registerInstance' of 'useInstancedMesh(...)' as it is undefined.
    at instance_1 (Instance.svelte? [sm]:13:9)
    at init (index.mjs:1876:11)
    at new Instance (Instance.svelte? [sm]:29:18)
    at createProxiedComponent (svelte-hooks.js:341:9)
    at new ProxyComponent (proxy.js:242:7)
    at new Proxy<Instance> (proxy.js:349:11)
    at create_each_block (Swarm.svelte:5:50)
    at Array.create_default_slot (Swarm.svelte:67:9)
    at create_slot (index.mjs:69:27)
    at Array.create_default_slot (InstancedMesh.svelte? [sm]:179:28)

I don't understand what I'm doing wrong, someone please can help ?

Thanks

**Comment by grischaerbe** [comment]
Hi @aozora,

You are passing an `id` to the instance, that is the problem.
The property id is used to use more multiple `<InstancedMesh>` providers. Refer to the docs for more information. In your case just leave out the property `id`.
Sorry, I'm on mobile and short on words.
Hope that helps!

**Comment by aozora** [comment]
Hi @grischaerbe , thank you for the effort, unfortunately removing the id from the <Instance> doesn't fix the scene.

I setup the code in this Codesandbox, however I'm getting another error.... this is so frustrating....
https://codesandbox.io/s/summer-shadow-5e0gwe?file=/App.svelte
